# -*- coding: utf-8 -*-
"""validar_identificacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oRyP04Z4o905gaIpDYT0vyr8uye7enJ
"""

!sudo apt-get install -y tesseract-ocr
!pip install pytesseract
!sudo apt-get install tesseract-ocr-por

from google.colab import files
uploaded = files.upload()

import pytesseract
from PIL import Image
import re

# Obter os nomes dos arquivos enviados
nomes_arquivos = list(uploaded.keys())

# Inicializar uma lista para armazenar os textos extraídos
textos_extraidos = []

# Processar cada imagem
for nome_arquivo in nomes_arquivos:
    imagem = Image.open(nome_arquivo)
    texto = pytesseract.image_to_string(imagem, lang='por')
    textos_extraidos.append(texto)

# Concatenar os textos extraídos
texto_completo = "\n".join(textos_extraidos)

# Função para validar CPF
def validar_cpf(cpf):
    cpf = re.sub(r'\D', '', cpf)
    if len(cpf) != 11 or cpf == cpf[0] * 11:
        return False
    for i in range(9, 11):
        soma = sum(int(cpf[num]) * ((i+1) - num) for num in range(0, i))
        digito = ((soma * 10) % 11) % 10
        if digito != int(cpf[i]):
            return False
    return True

# Solicitar dados ao usuário
nome_usuario = input("Digite o nome completo: ").strip().upper()
cpf_usuario = input("Digite o CPF (somente números): ").strip()

# Validar CPF
if not validar_cpf(cpf_usuario):
    print("CPF inválido.")
else:

    # Verificar se o nome e o CPF estão presentes no texto extraído
    nome_encontrado = nome_usuario in texto_completo
    cpf_encontrado = cpf_usuario in re.sub(r'\D', '', texto_completo)

    if nome_encontrado and cpf_encontrado:
        print("Nome e CPF encontrados no documento, identificacao valida!")
    elif nome_encontrado:
        print("Apenas nome encontrado no documento.")
    elif cpf_encontrado:
        print("Apenas CPF encontrado no documento.")
    else:
        print("Nome e CPF não encontrados no documento.")